### ISSUE TITLE
Create or Get Workspace using azure-cli-core 2.27.0 ERROR

### ISSUE THREAD

**Issue by Munyasya** [microsoft/azuredevopslabs#561]
2021-08-04T11:32:03.9676402Z ##[section]Starting: Create or Get Workspace
2021-08-04T11:32:03.9684698Z ==============================================================================
2021-08-04T11:32:03.9684957Z Task         : Azure CLI
2021-08-04T11:32:03.9685278Z Description  : Run Azure CLI commands against an Azure subscription in a Shell script when running on Linux agent or Batch script when running on Windows agent.
2021-08-04T11:32:03.9685696Z Version      : 1.164.0
2021-08-04T11:32:03.9685877Z Author       : Microsoft Corporation
2021-08-04T11:32:03.9686169Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2021-08-04T11:32:03.9686471Z ==============================================================================
2021-08-04T11:32:04.1185697Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az --version
2021-08-04T11:32:05.1454563Z 
2021-08-04T11:32:05.1455910Z azure-cli                         2.27.0
2021-08-04T11:32:05.1456781Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-08-04T11:32:05.1457107Z 
2021-08-04T11:32:05.1458326Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-08-04T11:32:05.1458763Z core                              2.27.0
2021-08-04T11:32:05.1459331Z telemetry                          1.0.6
2021-08-04T11:32:05.1459616Z 
2021-08-04T11:32:05.1459897Z Extensions:
2021-08-04T11:32:05.1460553Z azure-devops                      0.18.0
2021-08-04T11:32:05.1460811Z 
2021-08-04T11:32:05.1461799Z Python location '/opt/hostedtoolcache/Python/3.6.14/x64/bin/python'
2021-08-04T11:32:05.1462574Z Extensions directory '/opt/az/azcliextensions'
2021-08-04T11:32:05.1462934Z 
2021-08-04T11:32:05.1463393Z Python (Linux) 3.6.14 (default, Jul  5 2021, 20:52:02) 
2021-08-04T11:32:05.1463798Z [GCC 9.3.0]
2021-08-04T11:32:05.1463993Z 
2021-08-04T11:32:05.1464634Z Legal docs and information: aka.ms/AzureCliLegal
2021-08-04T11:32:05.1465056Z 
2021-08-04T11:32:05.1465213Z 
2021-08-04T11:32:05.1465692Z Your CLI is up-to-date.
2021-08-04T11:32:05.1506915Z Setting AZURE_CONFIG_DIR env variable to: /home/vsts/work/_temp/.azclitask
2021-08-04T11:32:05.1550321Z Setting active cloud to: AzureCloud
2021-08-04T11:32:05.1577086Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az cloud set -n AzureCloud
2021-08-04T11:32:06.5762868Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az login --service-principal -u *** --password=*** --tenant ***
2021-08-04T11:32:07.3486115Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-08-04T11:32:07.3487812Z ERROR: __init__() got an unexpected keyword argument 'user_agent'
2021-08-04T11:32:07.3489306Z Traceback (most recent call last):
2021-08-04T11:32:07.3530527Z ##[error]Error Code: [1]
2021-08-04T11:32:07.3542648Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
2021-08-04T11:32:07.3543124Z     cmd_result = self.invocation.execute(args)
2021-08-04T11:32:07.3544345Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
2021-08-04T11:32:07.3544935Z     raise ex
2021-08-04T11:32:07.3545526Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-08-04T11:32:07.3545999Z     results.append(self._run_job(expanded_arg, cmd_copy))
2021-08-04T11:32:07.3546665Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-08-04T11:32:07.3547101Z     result = cmd_copy(params)
2021-08-04T11:32:07.3547944Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
2021-08-04T11:32:07.3548392Z     return self.handler(*args, **kwargs)
2021-08-04T11:32:07.3549053Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2021-08-04T11:32:07.3549616Z     return op(**command_args)
2021-08-04T11:32:07.3550346Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 161, in login
2021-08-04T11:32:07.3550978Z     use_cert_sn_issuer=use_cert_sn_issuer)
2021-08-04T11:32:07.3551621Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 216, in find_subscriptions_on_login
2021-08-04T11:32:07.3552099Z     username, sp_auth, tenant, self._ad_resource_uri)
2021-08-04T11:32:07.3552822Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 939, in find_from_service_principal_id
2021-08-04T11:32:07.3553304Z     result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
2021-08-04T11:32:07.3554195Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 1033, in _find_using_specific_tenant
2021-08-04T11:32:07.3554666Z     client = self._arm_client_factory(token_credential)
2021-08-04T11:32:07.3555294Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 881, in create_arm_client_factory
2021-08-04T11:32:07.3555782Z     base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)
2021-08-04T11:32:07.3556541Z TypeError: __init__() got an unexpected keyword argument 'user_agent'
2021-08-04T11:32:07.3557026Z To open an issue, please run: 'az feedback'
2021-08-04T11:32:07.3557809Z ##[error]Error: Azure login failed
2021-08-04T11:32:07.3566596Z ##[error]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: __init__() got an unexpected keyword argument 'user_agent'

**Comment by sriramdasbalaji** [comment]
Hi @Munyasya ,

Could you please provide more details? In which lab you are facing this issue.

Thanks
