### ISSUE TITLE
50. Deploy Webservice on ACI error on 

### ISSUE THREAD

**Issue by Munyasya** [microsoft/azuredevopslabs#562]
2021-08-04T11:47:13.9014560Z ##[section]Starting: 50. Deploy Webservice on ACI
2021-08-04T11:47:13.9021878Z ==============================================================================
2021-08-04T11:47:13.9022160Z Task         : Azure CLI
2021-08-04T11:47:13.9022546Z Description  : Run Azure CLI commands against an Azure subscription in a Shell script when running on Linux agent or Batch script when running on Windows agent.
2021-08-04T11:47:13.9022900Z Version      : 1.164.0
2021-08-04T11:47:13.9023116Z Author       : Microsoft Corporation
2021-08-04T11:47:13.9023411Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2021-08-04T11:47:13.9023758Z ==============================================================================
2021-08-04T11:47:14.0255624Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az --version
2021-08-04T11:47:16.0688468Z WARNING: Unable to check if your CLI is up-to-date. Check your internet connection.
2021-08-04T11:47:16.0689062Z azure-cli                          2.2.0
2021-08-04T11:47:16.0689858Z 
2021-08-04T11:47:16.0690479Z command-modules-nspkg              2.0.3
2021-08-04T11:47:16.0690984Z core                               2.2.0
2021-08-04T11:47:16.0691462Z nspkg                              3.0.4
2021-08-04T11:47:16.0691934Z telemetry                          1.0.6
2021-08-04T11:47:16.0692249Z 
2021-08-04T11:47:16.0692619Z Extensions:
2021-08-04T11:47:16.0693227Z azure-devops                      0.18.0
2021-08-04T11:47:16.0693551Z 
2021-08-04T11:47:16.0694188Z Python location '/opt/hostedtoolcache/Python/3.6.14/x64/bin/python'
2021-08-04T11:47:16.0694883Z Extensions directory '/opt/az/azcliextensions'
2021-08-04T11:47:16.0695216Z 
2021-08-04T11:47:16.0695682Z Python (Linux) 3.6.14 (default, Jul  5 2021, 20:52:02) 
2021-08-04T11:47:16.0696163Z [GCC 9.3.0]
2021-08-04T11:47:16.0696445Z 
2021-08-04T11:47:16.0696869Z Legal docs and information: aka.ms/AzureCliLegal
2021-08-04T11:47:16.0697198Z 
2021-08-04T11:47:16.0697466Z 
2021-08-04T11:47:16.0697718Z 
2021-08-04T11:47:16.0697971Z 
2021-08-04T11:47:16.0701561Z Please let us know how we are doing: https://aka.ms/clihats
2021-08-04T11:47:16.0702870Z Setting AZURE_CONFIG_DIR env variable to: /home/vsts/work/_temp/.azclitask
2021-08-04T11:47:16.0704012Z Setting active cloud to: AzureCloud
2021-08-04T11:47:16.0708708Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az cloud set -n AzureCloud
2021-08-04T11:47:18.3220821Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az login --service-principal -u *** --password=*** --tenant ***
2021-08-04T11:47:19.6282401Z [
2021-08-04T11:47:19.6283136Z   {
2021-08-04T11:47:19.6283596Z     "cloudName": "AzureCloud",
2021-08-04T11:47:19.6285119Z     "homeTenantId": "***",
2021-08-04T11:47:19.6286393Z     "id": "xxxxxxx0",
2021-08-04T11:47:19.6286907Z     "isDefault": true,
2021-08-04T11:47:19.6287348Z     "managedByTenants": [
2021-08-04T11:47:19.6287772Z       {
2021-08-04T11:47:19.6288408Z         "tenantId": "2f4a9838-xxxxxxx"
2021-08-04T11:47:19.6288907Z       }
2021-08-04T11:47:19.6289292Z     ],
2021-08-04T11:47:19.6289731Z     "name": "Microsoft Azure Internal Consumption",
2021-08-04T11:47:19.6290216Z     "state": "Enabled",
2021-08-04T11:47:19.6291085Z     "tenantId": "***",
2021-08-04T11:47:19.6291538Z     "user": {
2021-08-04T11:47:19.6292316Z       "name": "***",
2021-08-04T11:47:19.6292795Z       "type": "servicePrincipal"
2021-08-04T11:47:19.6293204Z     }
2021-08-04T11:47:19.6293583Z   }
2021-08-04T11:47:19.6293959Z ]
2021-08-04T11:47:19.6302621Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az account set --subscription 614ef50c-2240-4765-9b10-748df74c5550
2021-08-04T11:47:20.3087755Z [command]/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1628077634020.sh
2021-08-04T11:47:21.5259229Z Failure while loading azureml_run_type_providers. Failed to load entrypoint automl = azureml.train.automl.run:AutoMLRun._from_run_dto with exception (numpy 1.14.5 (/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages), Requirement.parse('numpy>=1.16.6'), {'pyarrow'}).
2021-08-04T11:48:49.8229750Z Service deployment polling reached non-successful terminal state, current service state: Failed
2021-08-04T11:48:49.8230950Z Operation ID: d1f0ab71-b210-43ca-82f8-766e56b99471
2021-08-04T11:48:49.8231676Z More information can be found using '.get_logs()'
2021-08-04T11:48:49.8232135Z Error:
2021-08-04T11:48:49.8232507Z {
2021-08-04T11:48:49.8232919Z   "code": "AciDeploymentFailed",
2021-08-04T11:48:49.8233350Z   "statusCode": 400,
2021-08-04T11:48:49.8235560Z   "message": "Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'ruamel', please run print(service.get_logs()) to get details.",
2021-08-04T11:48:49.8236368Z   "details": [
2021-08-04T11:48:49.8236750Z     {
2021-08-04T11:48:49.8237170Z       "code": "CrashLoopBackOff",
2021-08-04T11:48:49.8238122Z       "message": "Error in entry script, ModuleNotFoundError: No module named 'ruamel', please run print(service.get_logs()) to get details."
2021-08-04T11:48:49.8238744Z     }
2021-08-04T11:48:49.8239105Z   ]
2021-08-04T11:48:49.8239447Z }
2021-08-04T11:48:49.8239691Z 
2021-08-04T11:48:49.8240380Z From image.json, Image used to deploy webservice on ACI: diabetes-model-score
2021-08-04T11:48:49.8240925Z Image Version: 1
2021-08-04T11:48:49.8241671Z Image Location = ee6e398cef0a494faa44c6bc1a4e3de2.azurecr.io/diabetes-model-score:1
2021-08-04T11:48:49.8242301Z Traceback (most recent call last):
2021-08-04T11:48:49.8243015Z   File "./aml_service/50-deployOnAci.py", line 75, in <module>
2021-08-04T11:48:49.8243633Z     service.wait_for_deployment()
2021-08-04T11:48:49.8244579Z   File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 925, in wait_for_deployment
2021-08-04T11:48:49.8245287Z     logs_response, format_error_response), logger=module_logger)
2021-08-04T11:48:49.8246073Z azureml.exceptions._azureml_exception.WebserviceException: WebserviceException:
2021-08-04T11:48:49.8247069Z 	Message: Service deployment polling reached non-successful terminal state, current service state: Failed
2021-08-04T11:48:49.8248024Z Operation ID: d1f0ab71-b210-43ca-82f8-766e56b99471
2021-08-04T11:48:49.8248715Z More information can be found using '.get_logs()'
2021-08-04T11:48:49.8249175Z Error:
2021-08-04T11:48:49.8249537Z {
2021-08-04T11:48:49.8249930Z   "code": "AciDeploymentFailed",
2021-08-04T11:48:49.8250377Z   "statusCode": 400,
2021-08-04T11:48:49.8251407Z   "message": "Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'ruamel', please run print(service.get_logs()) to get details.",
2021-08-04T11:48:49.8252102Z   "details": [
2021-08-04T11:48:49.8252703Z     {
2021-08-04T11:48:49.8253104Z       "code": "CrashLoopBackOff",
2021-08-04T11:48:49.8254053Z       "message": "Error in entry script, ModuleNotFoundError: No module named 'ruamel', please run print(service.get_logs()) to get details."
2021-08-04T11:48:49.8254677Z     }
2021-08-04T11:48:49.8255033Z   ]
2021-08-04T11:48:49.8255391Z }
2021-08-04T11:48:49.8255758Z 	InnerException None
2021-08-04T11:48:49.8256178Z 	ErrorResponse 
2021-08-04T11:48:49.8256535Z {
2021-08-04T11:48:49.8256897Z     "error": {
2021-08-04T11:48:49.8259493Z         "message": "Service deployment polling reached non-successful terminal state, current service state: Failed\nOperation ID: d1f0ab71-b210-43ca-82f8-766e56b99471\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"AciDeploymentFailed\",\n  \"statusCode\": 400,\n  \"message\": \"Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'ruamel', please run print(service.get_logs()) to get details.\",\n  \"details\": [\n    {\n      \"code\": \"CrashLoopBackOff\",\n      \"message\": \"Error in entry script, ModuleNotFoundError: No module named 'ruamel', please run print(service.get_logs()) to get details.\"\n    }\n  ]\n}"
2021-08-04T11:48:49.8261250Z     }
2021-08-04T11:48:49.8261597Z }
2021-08-04T11:48:49.9535763Z ##[error]Script failed with error: Error: The process '/usr/bin/bash' failed with exit code 1
2021-08-04T11:48:49.9550268Z [command]/opt/hostedtoolcache/Python/3.6.14/x64/bin/az account clear
2021-08-04T11:48:50.6227783Z ##[section]Finishing: 50. Deploy Webservice on ACI

**Comment by pavangatadi** [comment]
i am also facing same issue, please resolve the issue at earliest
