### ISSUE TITLE
DB deployment task failed

### ISSUE THREAD

**Issue by eoumenwa** [microsoft/azuredevopslabs#688]
Getting the error below when deploying the DB
2023-11-12T14:06:27.5985514Z ##[section]Starting: Azure SQL DacpacTask
2023-11-12T14:06:27.5992798Z ==============================================================================
2023-11-12T14:06:27.5993129Z Task         : Azure SQL Database deployment
2023-11-12T14:06:27.5993351Z Description  : Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
2023-11-12T14:06:27.5993793Z Version      : 1.225.1
2023-11-12T14:06:27.5993905Z Author       : Microsoft Corporation
2023-11-12T14:06:27.5994087Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment
2023-11-12T14:06:27.5994641Z ==============================================================================
2023-11-12T14:06:27.6125650Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2023-11-12T14:06:27.6137534Z ##[debug]System.InvalidOperationException: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() in /home/vsts/work/1/s/src/Agent.Worker/TaskRunner.cs:line 117
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in /home/vsts/work/1/s/src/Agent.Worker/StepsRunner.cs:line 238
2023-11-12T14:06:27.6142276Z ##[section]Finishing: Azure SQL DacpacTask

![image](https://github.com/microsoft/azuredevopslabs/assets/78841364/86673fe5-c818-4b12-a16d-dec21c4ed097)

See full logs
[ReleaseLogs_3.zip](https://github.com/microsoft/azuredevopslabs/files/13328248/ReleaseLogs_3.zip)

**Comment by surajshenoy** [comment]
Hi @eoumenwa,

Thanks again for trying out the lab.

This pipeline has been configured in template to **use 'Windows-2019' agent so that DB deployment** work without any issue. As per your logs it is using Ubuntu-22.04.

Will you please change the agent to Windows-2019 and give a try so that you will not get the above mentioned issue. You can use the below screenshot for reference.


![image](https://github.com/microsoft/azuredevopslabs/assets/36665779/a22ba716-c50b-4afb-a2b5-157bd31e28bb)

**Comment by jaysnanavati** [comment]
Hello,
May I please request to be removed from this list?

Thanks,
Jay
________________________________

**Comment by eoumenwa** [comment]
> Hi @eoumenwa,
> 
> Thanks again for trying out the lab.
> 
> This pipeline has been configured in template to **use 'Windows-2019' agent so that DB deployment** work without any issue. As per your logs it is using Ubuntu-22.04.
> 
> Will you please change the agent to Windows-2019 and give a try so that you will not get the above mentioned issue. You can use the below screenshot for reference.
> 
> ![image](https://user-images.githubusercontent.com/36665779/282426874-a22ba716-c50b-4afb-a2b5-157bd31e28bb.png)

This worked. Thanks
